using DSharpPlus.CommandsNext;
using DSharpPlus.CommandsNext.Attributes;
using DSharpPlus.Entities;
using Markov;
using SquidBot_Sharp.Modules;
using System;
using System.Threading.Tasks;

namespace SquidBot_Sharp.Commands
{
    public class ImpersonateCMD : BaseCommandModule
    {
        [Command("impersonate"), Description("Impersonate a user based on a Markov Chain")]
        [RequireOwner, Hidden]
        public async Task ImpersonateMarkov(CommandContext ctx, DiscordMember member)
        {
            var impersonation = new ImpersonateModule { };

            var usertext = await impersonation.LoadFile(member.Id.ToString());
            if(usertext.Length < 1)
            {
                await ctx.RespondAsync("No data detected for that user!");
                return;
            }

            // Start the markov chains
            var chain = new MarkovChain<string>(1);

            foreach(var entry in usertext)
            {
                var splitentry = entry.Split(" ");
                chain.Add(splitentry, 1);
            }
            var rand = new Random();

            string sentences = "";
            for (int i = 0; i < 10; i++)
            {
                sentences = string.Join(" ", chain.Chain(rand)) + "\n";
            }
            await ctx.RespondAsync($"`These messages were generated by Markov Chains`\nHere's an example of what {member.Username} sounds like:\n```\n{sentences}```");
            return;
        }
    }
}
