using DSharpPlus.CommandsNext;
using DSharpPlus.CommandsNext.Attributes;
using DSharpPlus.Entities;
using Markov;
using SquidBot_Sharp.Modules;
using System;
using System.Threading.Tasks;
using System.Linq;

namespace SquidBot_Sharp.Commands
{
    public class ImpersonateCMD : BaseCommandModule
    {
        [Command("impersonate"), Description("Impersonate a user using a random AI method")]
        [Cooldown(1, 60, CooldownBucketType.User)]
        public async Task Impersonate(CommandContext ctx, DiscordMember member)
        {
            await ctx.RespondAsync("Generating impersonation (this might take a second!)");
            var userStrings = await DatabaseModule.GetUserMessages(member.Id);
            if(DatabaseModule.HitException != null)
            {
                await ctx.RespondAsync($"An error occured: {DatabaseModule.HitException.Message}");
                return;
            }
            var ListArray = userStrings.ToArray();

            if (ListArray.Length < 1)
            {
                await ctx.RespondAsync("No data detected for that user!");
                return;
            }

            if (ListArray.Length < 100)
            {
                await ctx.RespondAsync($"{member.Username} is currently at **{ListArray.Length}%** of minimum data needed to impersonate.");
                return;
            }
            await ImpersonateMarkov(ctx, member, ListArray);
        }

        [Command("impersonateall"), Description("Generate an impersonation from all collected message data")]
        [Cooldown(1, 60, CooldownBucketType.User)]
        public async Task ImpersonateAll(CommandContext ctx)
        {
            await ctx.RespondAsync("Generating impersonation (this might take a second!)");
            var userStrings = await DatabaseModule.GetAllMessages();
            if (DatabaseModule.HitException != null)
            {
                await ctx.RespondAsync($"An error occured: {DatabaseModule.HitException.Message}");
                return;
            }
            var ListArray = userStrings.ToArray();
            await ImpersonateMarkov(ctx, null, ListArray);
        }


        public async Task ImpersonateMarkov(CommandContext ctx, DiscordMember member, string[] usertext)
        {

            // Start the markov chains
            var chain = new MarkovChain<string>(1);

            foreach(var entry in usertext)
            {
                var splitentry = entry.Split(" ");
                int currWeight = 1;
                for(double i = 0; i < splitentry.Length; i += 1)
                {
                    currWeight++;
                }
                if (currWeight > 10) currWeight = 10;
                chain.Add(splitentry, currWeight);
            }
            var rand = new Random();

            string sentences = "";
            for (int i = 0; i < 5; i++)
            {
                sentences += "```\n" + string.Join(" ", chain.Chain(rand)).Replace('`', ' ').Replace('\n', ' ') + "```";
            }
            if (member == null)
            {
                await ctx.RespondAsync($"`These messages were generated by Markov Chains`\nHere are some examples of what all collected data sounds like ({usertext.Length} data points):\n{sentences}");
            }
            else
            {
                await ctx.RespondAsync($"`These messages were generated by Markov Chains`\nHere are some examples of what {member.Username} sounds like ({usertext.Length} data points):\n{sentences}");
            }
            return;
        }
    }
}
